# ---- Этап 1: Сборка с Maven ----
FROM dockerhub.timeweb.cloud/library/maven:3.8.5-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# ---- Этап 2: Финальный образ для запуска ----
FROM dockerhub.timeweb.cloud/library/eclipse-temurin:17-jre-alpine
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
COPY --from=builder --chown=appuser:appgroup /build/target/*.jar app.jar
USER appuser
ENTRYPOINT ["java", "-jar", "app.jar"]
